import Link from 'next/link'
import Header from '../../components/Header'
import Footer from '../../components/Footer'

export const metadata = {
  title: 'Crawl Space Waterproofing in Alpharetta, GA | Free Inspection | Reliable Solutions Atlanta',
  description: 'Crawl space waterproofing in Alpharetta, GA. Interior drainage, sump pumps, and vapor barriers for North Fulton homes with failing builder-grade protection. Most projects $2,500-$8,000. Free inspection. 770-895-2039.',
  keywords: 'crawl space waterproofing Alpharetta GA, crawl space water North Fulton, wet crawl space Alpharetta, crawl space drainage Alpharetta Georgia',
  openGraph: { title: 'Crawl Space Waterproofing in Alpharetta, GA | Reliable Solutions Atlanta', description: 'Stop water in your Alpharetta crawl space. Free inspections. 770-895-2039.', url: 'https://www.waterhelpme.com/crawl-space-waterproofing/alpharetta', type: 'website' },
  alternates: { canonical: 'https://www.waterhelpme.com/crawl-space-waterproofing/alpharetta' },
}

const faqs = [
  { question: 'How much does crawl space waterproofing cost in Alpharetta, GA?', answer: 'Crawl space waterproofing in Alpharetta typically costs between $2,500 and $8,000. Many Alpharetta homes have smaller crawl space sections combined with slab areas, which reduces the scope compared to full crawl space homes. Interior drainage with sump pump starts around $2,500. Full waterproofing with perimeter drain and vapor barrier runs $5,000 to $10,000.' },
  { question: 'Why does my newer Alpharetta home have crawl space water?', answer: 'Homes built in the 1990s and 2000s in Alpharetta used fill soil to level lots that was not always properly compacted. After 15 to 25 years, this fill has settled, creating gaps between the soil and foundation that channel water into the crawl space. The original 6-mil vapor barrier and damproofing have also deteriorated by this point.' },
  { question: 'My Alpharetta home has both slab and crawl space sections. Can you waterproof just the crawl space?', answer: 'Yes. Many Alpharetta homes on rolling terrain have a slab foundation on one end and a crawl space where the grade drops. We waterproof just the crawl space section and seal the transition to the slab so moisture cannot migrate between the two areas. This is common in Windward, Cambridge, and Thornberry subdivisions.' },
  { question: 'Will my Alpharetta HOA have issues with waterproofing work?', answer: 'Crawl space waterproofing is interior work that does not affect the exterior appearance of your home. Most Alpharetta HOAs have no restrictions on below-grade interior improvements. The sump pump discharge line exits at grade level and can be routed to comply with any HOA drainage requirements.' },
  { question: 'Can waterproofing fix the musty smell in my Alpharetta home?', answer: 'Yes. The musty odor comes from mold and mildew in the damp crawl space. Waterproofing stops the water entry, and a proper vapor barrier prevents ground moisture from evaporating into the crawl space air. Adding a dehumidifier provides complete humidity control. Most homeowners notice the smell reducing within the first week.' },
]

export default function CrawlSpaceWaterproofingAlpharetta() {
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Service', name: 'Crawl Space Waterproofing in Alpharetta, GA', provider: { '@type': 'LocalBusiness', name: 'Reliable Solutions Atlanta', telephone: '+17708952039', url: 'https://www.waterhelpme.com', address: { '@type': 'PostalAddress', addressLocality: 'Alpharetta', addressRegion: 'GA', addressCountry: 'US' }, areaServed: { '@type': 'City', name: 'Alpharetta', containedIn: 'Fulton County, GA' } }, serviceType: 'Crawl Space Waterproofing' }
  const faqJsonLd = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }

  return (
    <>
      <Header />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />

      <section className="relative bg-[#273373] py-16 sm:py-20 md:py-28"><div className="absolute inset-0 bg-gradient-to-br from-[#273373] to-[#115997] opacity-90" /><div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-white/70 text-sm font-medium mb-3 uppercase tracking-wider">North Fulton County, Georgia</p><h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-6 font-display leading-tight">Crawl Space Waterproofing in Alpharetta, GA</h1><p className="text-white/80 text-lg sm:text-xl mb-8 leading-relaxed max-w-2xl">Crawl space waterproofing in Alpharetta typically costs between $2,500 and $8,000. Reliable Solutions Atlanta stops water in North Fulton crawl spaces where builder-grade protection has failed after 15 to 25 years. Interior drainage, sump pumps, and heavy-duty vapor barriers for Alpharetta subdivisions. Free same-week inspections.</p><div className="flex flex-col sm:flex-row gap-3"><Link href="/contact" className="inline-flex items-center justify-center gap-2 px-6 py-4 bg-white text-[#273373] font-bold rounded-xl hover:bg-gray-100 transition-colors">Schedule Free Inspection</Link><a href="tel:+17708952039" className="inline-flex items-center justify-center gap-2 px-6 py-4 bg-transparent border-2 border-white/30 text-white font-bold rounded-xl hover:bg-white/10 transition-colors">(770) 895-2039</a></div></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Why Alpharetta Crawl Spaces Take On Water</h2><div className="prose prose-lg max-w-none text-gray-700"><p>Alpharetta homes built during the North Fulton building boom of the 1990s and 2000s used the minimum crawl space protection required by code at the time. A thin 6-mil vapor barrier on the dirt floor and open foundation vents were considered adequate. After 15 to 25 years, the barriers have torn, displaced, or degraded, and the vents admit humid air that condenses on cooler crawl space surfaces throughout the summer months.</p><p>The fill soil used to level lots in subdivisions like Windward, Broadwell Oaks, Thornberry, Cambridge, and Cogburn Station in the 30004, 30005, 30009, and 30022 zip codes has continued to settle over the decades. As the fill compacts, it pulls away from the foundation wall, creating channels that direct surface water straight to the crawl space. The original damproofing on the exterior walls was never designed to handle this concentrated water delivery.</p><p>Many Alpharetta homes have a hybrid foundation with slab on one end and crawl space on the other, built to accommodate the rolling North Fulton terrain. The transition between slab and crawl space creates a stress point where water can enter if the joint is not properly sealed, and these joints were rarely waterproofed during original construction.</p></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Signs Your Alpharetta Crawl Space Needs Waterproofing</h2><div className="grid sm:grid-cols-2 gap-4">{[{ title: 'Standing water after rain events', desc: 'If water pools in the crawl space during or after rain and takes days to recede, the foundation is admitting water under hydrostatic pressure. A vapor barrier alone cannot stop pressurized water.' },{ title: 'Torn or displaced builder vapor barrier', desc: 'Check the crawl space access. If the original plastic is bunched up, torn, or only covering part of the floor, the crawl space has had no effective moisture protection for years.' },{ title: 'Condensation on ductwork and pipes', desc: 'Water droplets on HVAC ducts and plumbing in the crawl space mean humidity is above the dew point. This condensation drips onto the structure and adds to the moisture load.' },{ title: 'Musty odor that peaks in summer', desc: 'Warm humid air entering through open vents condenses in the cooler crawl space from May through September. The musty smell follows this seasonal pattern, confirming the crawl space is the source.' },{ title: 'Fiberglass insulation sagging or fallen', desc: 'Batt insulation between floor joists that has absorbed moisture and sagged or fallen is a clear indicator the crawl space humidity has exceeded safe levels for an extended period.' },{ title: 'Higher energy bills than similar Alpharetta homes', desc: 'An unsealed wet crawl space adds a moisture and temperature load to your HVAC that neighbors with dry crawl spaces do not have. If your bills seem high for your home size, the crawl space may be the reason.' }].map((sign, i) => (<div key={i} className="bg-white rounded-xl p-5 shadow-sm"><h3 className="font-semibold text-[#273373] text-base mb-2">{sign.title}</h3><p className="text-gray-600 text-sm leading-relaxed">{sign.desc}</p></div>))}</div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">How We Waterproof Crawl Spaces in Alpharetta</h2><div className="prose prose-lg max-w-none text-gray-700"><h3 className="text-[#273373] font-display">Interior French Drain Along Foundation Walls</h3><p>We install a perimeter French drain inside the crawl space along the walls where water enters. The drain sits in a gravel bed that captures water at the wall-footer joint and routes it to a centrally located sump pit. For Alpharetta homes with partial crawl spaces, we size the drain system to the actual crawl space footprint rather than a standard full-perimeter install.</p><h3 className="text-[#273373] font-display">Slab-to-Crawl Transition Sealing</h3><p>Where the crawl space meets a slab section in hybrid Alpharetta homes, we seal the transition joint with hydraulic cement and apply a flexible membrane that accommodates minor movement. This prevents water from migrating between the two foundation types through the unsealed joint that builders left during original construction.</p><h3 className="text-[#273373] font-display">Sump Pump with HOA-Compliant Discharge</h3><p>The sump pump collects water from the perimeter drain and discharges it through a line that exits at grade level. For Alpharetta HOA communities, we route the discharge to comply with community drainage requirements, avoiding discharge onto sidewalks, common areas, or neighboring properties. Battery backup is included for storm-driven power outages.</p><h3 className="text-[#273373] font-display">20-Mil Vapor Barrier Replacement</h3><p>We remove the old builder-grade barrier and install a 20-mil reinforced liner across the floor and up the walls. This is over three times thicker than the original 6-mil plastic and is sealed at every seam, pier, and penetration. The difference in moisture blocking performance is dramatic and immediate.</p></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Crawl Space Waterproofing Costs in Alpharetta</h2><div className="bg-white rounded-xl shadow-sm overflow-hidden"><table className="w-full"><thead className="bg-[#273373] text-white"><tr><th className="px-6 py-4 text-left text-sm font-semibold">Service</th><th className="px-6 py-4 text-left text-sm font-semibold">Typical Cost</th><th className="px-6 py-4 text-left text-sm font-semibold hidden sm:table-cell">Timeline</th></tr></thead><tbody className="divide-y divide-gray-100">{[['Vapor barrier upgrade (20-mil)', '$1,500 – $3,500', '1 day'],['Interior perimeter drain + sump', '$2,500 – $6,000', '1-2 days'],['Full waterproofing system', '$4,000 – $10,000', '2-3 days'],['Slab-to-crawl transition sealing', '$500 – $1,200', 'Same day'],['Sump pump with battery backup', '$1,500 – $2,500', '1 day'],['Partial crawl space waterproofing', '$2,000 – $5,000', '1-2 days']].map(([r, c, t], i) => (<tr key={i} className="hover:bg-gray-50"><td className="px-6 py-4 text-sm text-gray-900">{r}</td><td className="px-6 py-4 text-sm font-semibold text-[#115997]">{c}</td><td className="px-6 py-4 text-sm text-gray-500 hidden sm:table-cell">{t}</td></tr>))}</tbody></table></div><p className="text-sm text-gray-500 mt-4">Financing available through GreenSky. Transferable warranty included.</p></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-8 font-display">Frequently Asked Questions</h2><div className="space-y-4">{faqs.map((faq, i) => (<div key={i} className="bg-gray-50 rounded-xl p-6"><h3 className="font-semibold text-[#273373] text-lg mb-3">{faq.question}</h3><p className="text-gray-700 leading-relaxed">{faq.answer}</p></div>))}</div></div></section>

      <section className="py-12 sm:py-16 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-[#273373] mb-6 font-display">Related Services in Alpharetta</h2><div className="grid sm:grid-cols-3 gap-4">{[{ title: 'Crawl Space Encapsulation', href: '/crawl-space-encapsulation/alpharetta', desc: 'After waterproofing stops the water, encapsulation seals and conditions the space.' },{ title: 'Foundation Repair', href: '/foundation-repair/alpharetta', desc: 'Fix settling foundation issues alongside crawl space waterproofing.' },{ title: 'Drainage Solutions', href: '/drainage/alpharetta', desc: 'Exterior drainage reduces water volume reaching your crawl space.' }].map((s, i) => (<Link key={i} href={s.href} className="bg-white rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow group"><h3 className="font-semibold text-[#273373] mb-2 group-hover:text-[#115997] transition-colors">{s.title}</h3><p className="text-gray-600 text-sm">{s.desc}</p></Link>))}</div></div></section>

      <section className="py-12 sm:py-16 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-[#273373] mb-6 font-display">Learn More About Crawl Spaces</h2><div className="grid sm:grid-cols-2 gap-4">{[{ title: 'Crawl Space Encapsulation vs Waterproofing', href: '/blog/crawl-space-encapsulation-vs-waterproofing' }, { title: 'Crawl Space Vapor Barrier Guide', href: '/blog/crawl-space-vapor-barrier-guide' }, { title: 'Crawl Space Mold: Signs and Solutions', href: '/blog/crawl-space-mold-signs' }, { title: 'Crawl Space Repair Cost in Atlanta', href: '/blog/crawl-space-repair-cost-atlanta' }].map((p, i) => (<Link key={i} href={p.href} className="flex items-center gap-3 p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors"><svg className="w-5 h-5 text-[#115997] flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg><span className="text-sm font-medium text-gray-800">{p.title}</span></Link>))}</div></div></section>

      <section className="py-8 bg-gray-50 border-t border-gray-200"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><p className="text-sm text-gray-500 mb-4"><Link href="/" className="hover:text-[#115997]">Home</Link> {' / '}<Link href="/crawl-space-waterproofing" className="hover:text-[#115997]">Crawl Space Waterproofing</Link> {' / '}<span className="text-gray-700">Alpharetta</span></p><p className="text-sm text-gray-500">Crawl space waterproofing also available in <Link href="/crawl-space-waterproofing/lawrenceville" className="text-[#115997] hover:underline">Lawrenceville</Link>, <Link href="/crawl-space-waterproofing/marietta" className="text-[#115997] hover:underline">Marietta</Link>, <Link href="/crawl-space-waterproofing/roswell" className="text-[#115997] hover:underline">Roswell</Link>, <Link href="/crawl-space-waterproofing/decatur" className="text-[#115997] hover:underline">Decatur</Link>, <Link href="/crawl-space-waterproofing/sandy-springs" className="text-[#115997] hover:underline">Sandy Springs</Link>, and <Link href="/crawl-space-waterproofing/stone-mountain" className="text-[#115997] hover:underline">Stone Mountain</Link>.</p></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-[#115997]"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-4 font-display">Free Crawl Space Inspection in Alpharetta</h2><p className="text-white/80 text-lg mb-8 max-w-2xl mx-auto">We will inspect your Alpharetta crawl space, document the condition of the existing protection, and give you a clear waterproofing plan with pricing. No obligation.</p><div className="flex flex-col sm:flex-row gap-3 justify-center"><Link href="/contact" className="inline-flex items-center justify-center px-8 py-4 bg-white text-[#273373] font-bold rounded-xl hover:bg-gray-100 transition-colors text-lg">Schedule Free Inspection</Link><a href="tel:+17708952039" className="inline-flex items-center justify-center px-8 py-4 border-2 border-white text-white font-bold rounded-xl hover:bg-white/10 transition-colors text-lg">Call (770) 895-2039</a></div><p className="text-white/50 text-sm mt-6">BBB A+ Accredited · IICRC Certified · 20+ Years Experience · Financing Available</p></div></section>
      <Footer />
    </>
  )
}