import Link from 'next/link'
import Header from '../../components/Header'
import Footer from '../../components/Footer'

export const metadata = {
  title: 'Crawl Space Waterproofing in Decatur, GA | Free Inspection | Reliable Solutions Atlanta',
  description: 'Crawl space waterproofing in Decatur, GA. Stop water in historic home crawl spaces. Interior drainage, sump pumps, vapor barriers for DeKalb County homes. Most projects $3,500-$10,000. Free inspection. 770-895-2039.',
  keywords: 'crawl space waterproofing Decatur GA, crawl space water DeKalb County, wet crawl space Decatur, historic home crawl space waterproofing Decatur Georgia',
  openGraph: { title: 'Crawl Space Waterproofing in Decatur, GA | Reliable Solutions Atlanta', description: 'Stop water in your Decatur crawl space. Historic home specialists. Free inspections. 770-895-2039.', url: 'https://www.waterhelpme.com/crawl-space-waterproofing/decatur', type: 'website' },
  alternates: { canonical: 'https://www.waterhelpme.com/crawl-space-waterproofing/decatur' },
}

const faqs = [
  { question: 'How much does crawl space waterproofing cost in Decatur, GA?', answer: 'Crawl space waterproofing in Decatur typically costs between $3,500 and $10,000. Historic homes with original fieldstone or brick foundations require more customized drainage solutions that cost more than standard block wall systems. Simple vapor barrier and sump starts around $2,500. Full waterproofing with drainage and structural repair runs $8,000 to $16,000.' },
  { question: 'Why are Decatur crawl spaces the wettest in metro Atlanta?', answer: 'Decatur has the oldest housing stock with zero original waterproofing, the densest tree canopy that prevents soil drying, and clay soil that holds water indefinitely. Homes from the early 1900s through 1940s in Oakhurst, Winnona Park, and Great Lakes were built with bare dirt floors and fieldstone foundations that freely admit water.' },
  { question: 'Can you waterproof a crawl space with a stone foundation?', answer: 'Yes. Stacked fieldstone and rubble stone foundations in Decatur cannot be sealed like poured concrete. Instead, we install a drainage system that collects water as it enters through the irregular wall and routes it to a sump pump. A dimpled membrane on the wall face channels water downward to the drain rather than into the crawl space.' },
  { question: 'Should I waterproof during my Decatur home renovation?', answer: 'The best time to waterproof a Decatur crawl space is during a renovation when contractors are already on site. We coordinate with general contractors to integrate waterproofing into the overall project scope. This is more cost-effective than doing it separately and ensures the crawl space is protected before new finish work goes in above.' },
  { question: 'Will waterproofing fix the bouncy floors in my Decatur bungalow?', answer: 'Waterproofing stops the water that causes the wood damage, but floors that are already bouncy need structural repair as well. We typically pair waterproofing with joist sistering and pier replacement so the crawl space is both dry and structurally sound. The waterproofing prevents the repaired structure from deteriorating again.' },
]

export default function CrawlSpaceWaterproofingDecatur() {
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Service', name: 'Crawl Space Waterproofing in Decatur, GA', provider: { '@type': 'LocalBusiness', name: 'Reliable Solutions Atlanta', telephone: '+17708952039', url: 'https://www.waterhelpme.com', address: { '@type': 'PostalAddress', addressLocality: 'Decatur', addressRegion: 'GA', addressCountry: 'US' }, areaServed: { '@type': 'City', name: 'Decatur', containedIn: 'DeKalb County, GA' } }, serviceType: 'Crawl Space Waterproofing' }
  const faqJsonLd = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }

  return (
    <>
      <Header />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />

      <section className="relative bg-[#273373] py-16 sm:py-20 md:py-28"><div className="absolute inset-0 bg-gradient-to-br from-[#273373] to-[#115997] opacity-90" /><div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-white/70 text-sm font-medium mb-3 uppercase tracking-wider">DeKalb County, Georgia</p><h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-6 font-display leading-tight">Crawl Space Waterproofing in Decatur, GA</h1><p className="text-white/80 text-lg sm:text-xl mb-8 leading-relaxed max-w-2xl">Crawl space waterproofing in Decatur typically costs between $3,500 and $10,000. Reliable Solutions Atlanta specializes in stopping water in the century-old crawl spaces beneath Decatur bungalows and craftsman homes that were built without any moisture protection. Interior drainage, sump pumps, vapor barriers, and stone wall membrane systems. Free same-week inspections.</p><div className="flex flex-col sm:flex-row gap-3"><Link href="/contact" className="inline-flex items-center justify-center gap-2 px-6 py-4 bg-white text-[#273373] font-bold rounded-xl hover:bg-gray-100 transition-colors">Schedule Free Inspection</Link><a href="tel:+17708952039" className="inline-flex items-center justify-center gap-2 px-6 py-4 bg-transparent border-2 border-white/30 text-white font-bold rounded-xl hover:bg-white/10 transition-colors">(770) 895-2039</a></div></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Why Decatur Crawl Spaces Take On Water</h2><div className="prose prose-lg max-w-none text-gray-700"><p>Decatur crawl spaces are the most water-prone in metro Atlanta because the homes were built before crawl space waterproofing existed as a concept. The bungalows, Tudor revivals, and colonial homes in Oakhurst, Winnona Park, Great Lakes, and the MAK District in the 30030, 30032, and 30033 zip codes were constructed from 1900 through the 1940s with crawl spaces that have bare dirt floors, stacked fieldstone or brick foundations, and no vapor barrier of any kind.</p><p>Water enters these crawl spaces from every direction. Ground moisture evaporates upward through the bare dirt floor. Rain water seeps through the gaps between fieldstones in the foundation wall. Surface runoff flows under the foundation where the stone meets the soil. And in areas near creeks and low spots, the water table itself can rise into the crawl space during wet seasons.</p><p>The dense tree canopy that makes Decatur neighborhoods so desirable compounds the moisture problem. The canopy prevents sunlight from reaching the soil surface, which means the ground around these homes never dries. Leaf litter creates an organic layer that holds moisture like a sponge. The soil stays perpetually saturated, maintaining constant hydrostatic pressure against the crawl space walls and floor.</p><p>Many Decatur homes have been renovated extensively above the crawl space while the space below was ignored. New kitchens, bathrooms, hardwood floors, and second-story additions sit on floor systems that have been absorbing moisture for a century. The renovation adds weight to structure that has been weakened by decades of water exposure.</p></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Signs Your Decatur Crawl Space Needs Waterproofing</h2><div className="grid sm:grid-cols-2 gap-4">{[{ title: 'Standing water on bare dirt floor', desc: 'Original Decatur crawl spaces with dirt floors that hold standing water have active water entry that needs drainage, not just a vapor barrier. The water source must be captured and routed out before any barrier goes down.' },{ title: 'Water seeping between fieldstones', desc: 'Watch the crawl space foundation wall during or after rain. If you see water trickling between the stones in the wall, the soil outside is saturated and pushing water through every gap in the irregular stone surface.' },{ title: 'Severe mold covering joists and subfloor', desc: 'In the worst Decatur crawl spaces, mold covers nearly every wood surface in a continuous layer. This level of growth indicates humidity has been above 70% consistently for years and the wood has been at high moisture content.' },{ title: 'Floors sloping or bouncing upstairs', desc: 'When the wooden piers, girders, and joists in a Decatur bungalow crawl space deteriorate from moisture, the floor system above loses support. Sloping or bouncing floors mean the structure has weakened significantly.' },{ title: 'Musty smell that never goes away', desc: 'In Decatur homes with minimal separation between crawl space and living area, the musty odor is constant. It does not come and go seasonally because the crawl space is perpetually wet. Guests notice it immediately.' },{ title: 'Termite damage found during inspection', desc: 'Annual termite inspections in Decatur homes frequently find damage in the crawl space. Subterranean termites need moisture to survive, and a wet crawl space with untreated wood is their ideal environment.' }].map((sign, i) => (<div key={i} className="bg-white rounded-xl p-5 shadow-sm"><h3 className="font-semibold text-[#273373] text-base mb-2">{sign.title}</h3><p className="text-gray-600 text-sm leading-relaxed">{sign.desc}</p></div>))}</div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">How We Waterproof Crawl Spaces in Decatur</h2><div className="prose prose-lg max-w-none text-gray-700"><h3 className="text-[#273373] font-display">Stone Wall Dimpled Membrane</h3><p>Decatur fieldstone and rubble stone foundation walls cannot be sealed conventionally because the surface is too irregular. We install a dimpled HDPE membrane on the interior wall face that creates an air gap. Water seeping through the stones hits the membrane and flows downward by gravity to the perimeter drain at the base. The crawl space side of the membrane stays dry.</p><h3 className="text-[#273373] font-display">Interior French Drain on Dirt Floor</h3><p>We trench a perimeter drain channel into the dirt floor along the foundation walls. The drain sits in a gravel bed that provides storage during heavy water events. Perforated pipe in the gravel collects water from the wall membrane, the floor surface, and subsurface water pushing up from below. Everything routes to the sump pit at the lowest point.</p><h3 className="text-[#273373] font-display">Sump Pump with Redundancy</h3><p>For Decatur crawl spaces with high water volume, we install a primary pump with battery backup. Homes with the most severe conditions may need a dual-pump system where two pumps alternate to handle peak flow. The discharge line routes through the foundation to a daylight point at least 15 feet from the house.</p><h3 className="text-[#273373] font-display">20-Mil Vapor Barrier Over Drainage</h3><p>After the drainage system is in place, a 20-mil reinforced vapor barrier covers the entire floor and wall surface over the membrane. The barrier prevents ground moisture vapor from entering the crawl space air while the drainage beneath handles liquid water. All seams are sealed and the barrier is fastened mechanically to the wall.</p></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Crawl Space Waterproofing Costs in Decatur</h2><div className="bg-white rounded-xl shadow-sm overflow-hidden"><table className="w-full"><thead className="bg-[#273373] text-white"><tr><th className="px-6 py-4 text-left text-sm font-semibold">Service</th><th className="px-6 py-4 text-left text-sm font-semibold">Typical Cost</th><th className="px-6 py-4 text-left text-sm font-semibold hidden sm:table-cell">Timeline</th></tr></thead><tbody className="divide-y divide-gray-100">{[['Stone wall dimpled membrane', '$2,000 – $4,500', '1 day'],['Interior perimeter drain + sump', '$3,000 – $7,000', '1-2 days'],['20-mil vapor barrier (floor + walls)', '$2,500 – $5,000', '1-2 days'],['Full waterproofing system', '$5,000 – $12,000', '2-4 days'],['Waterproofing + structural repair', '$8,000 – $18,000', '3-6 days'],['Mold treatment before waterproofing', '$1,500 – $3,500', '1 day']].map(([r, c, t], i) => (<tr key={i} className="hover:bg-gray-50"><td className="px-6 py-4 text-sm text-gray-900">{r}</td><td className="px-6 py-4 text-sm font-semibold text-[#115997]">{c}</td><td className="px-6 py-4 text-sm text-gray-500 hidden sm:table-cell">{t}</td></tr>))}</tbody></table></div><p className="text-sm text-gray-500 mt-4">Financing available through GreenSky. All waterproofing work includes transferable warranty.</p></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-8 font-display">Frequently Asked Questions</h2><div className="space-y-4">{faqs.map((faq, i) => (<div key={i} className="bg-gray-50 rounded-xl p-6"><h3 className="font-semibold text-[#273373] text-lg mb-3">{faq.question}</h3><p className="text-gray-700 leading-relaxed">{faq.answer}</p></div>))}</div></div></section>

      <section className="py-12 sm:py-16 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-[#273373] mb-6 font-display">Related Services in Decatur</h2><div className="grid sm:grid-cols-3 gap-4">{[{ title: 'Crawl Space Encapsulation', href: '/crawl-space-encapsulation/decatur', desc: 'Seal and condition the crawl space after waterproofing for complete moisture control.' },{ title: 'Foundation Repair', href: '/foundation-repair/decatur', desc: 'Replace century-old pier foundations alongside waterproofing for total structural restoration.' },{ title: 'Crawl Space Repair', href: '/crawl-space-repair', desc: 'Structural repair for moisture-damaged joists, girders, and piers in Decatur homes.' }].map((s, i) => (<Link key={i} href={s.href} className="bg-white rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow group"><h3 className="font-semibold text-[#273373] mb-2 group-hover:text-[#115997] transition-colors">{s.title}</h3><p className="text-gray-600 text-sm">{s.desc}</p></Link>))}</div></div></section>

      <section className="py-12 sm:py-16 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-[#273373] mb-6 font-display">Learn More About Crawl Spaces</h2><div className="grid sm:grid-cols-2 gap-4">{[{ title: 'Crawl Space Repair Cost in Atlanta', href: '/blog/crawl-space-repair-cost-atlanta' }, { title: 'Crawl Space Mold: Signs and Solutions', href: '/blog/crawl-space-mold-signs' }, { title: 'Crawl Space Encapsulation vs Waterproofing', href: '/blog/crawl-space-encapsulation-vs-waterproofing' }, { title: 'Crawl Space Vapor Barrier Guide', href: '/blog/crawl-space-vapor-barrier-guide' }].map((p, i) => (<Link key={i} href={p.href} className="flex items-center gap-3 p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors"><svg className="w-5 h-5 text-[#115997] flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg><span className="text-sm font-medium text-gray-800">{p.title}</span></Link>))}</div></div></section>

      <section className="py-8 bg-gray-50 border-t border-gray-200"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><p className="text-sm text-gray-500 mb-4"><Link href="/" className="hover:text-[#115997]">Home</Link> {' / '}<Link href="/crawl-space-waterproofing" className="hover:text-[#115997]">Crawl Space Waterproofing</Link> {' / '}<span className="text-gray-700">Decatur</span></p><p className="text-sm text-gray-500">Crawl space waterproofing also available in <Link href="/crawl-space-waterproofing/lawrenceville" className="text-[#115997] hover:underline">Lawrenceville</Link>, <Link href="/crawl-space-waterproofing/marietta" className="text-[#115997] hover:underline">Marietta</Link>, <Link href="/crawl-space-waterproofing/roswell" className="text-[#115997] hover:underline">Roswell</Link>, <Link href="/crawl-space-waterproofing/alpharetta" className="text-[#115997] hover:underline">Alpharetta</Link>, <Link href="/crawl-space-waterproofing/sandy-springs" className="text-[#115997] hover:underline">Sandy Springs</Link>, and <Link href="/crawl-space-waterproofing/stone-mountain" className="text-[#115997] hover:underline">Stone Mountain</Link>.</p></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-[#115997]"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-4 font-display">Free Crawl Space Inspection in Decatur</h2><p className="text-white/80 text-lg mb-8 max-w-2xl mx-auto">We understand Decatur historic construction. We will inspect your crawl space, document everything with photos, and give you an honest waterproofing plan. No obligation.</p><div className="flex flex-col sm:flex-row gap-3 justify-center"><Link href="/contact" className="inline-flex items-center justify-center px-8 py-4 bg-white text-[#273373] font-bold rounded-xl hover:bg-gray-100 transition-colors text-lg">Schedule Free Inspection</Link><a href="tel:+17708952039" className="inline-flex items-center justify-center px-8 py-4 border-2 border-white text-white font-bold rounded-xl hover:bg-white/10 transition-colors text-lg">Call (770) 895-2039</a></div><p className="text-white/50 text-sm mt-6">BBB A+ Accredited · IICRC Certified · 20+ Years Experience · Financing Available</p></div></section>
      <Footer />
    </>
  )
}