import Link from 'next/link'
import Header from '../../components/Header'
import Footer from '../../components/Footer'

export const metadata = {
  title: 'Crawl Space Waterproofing in Stone Mountain, GA | Free Inspection | Reliable Solutions Atlanta',
  description: 'Crawl space waterproofing in Stone Mountain, GA. Stop granite-channeled water from flooding your crawl space. Interior drainage, sump pumps, vapor barriers. Most projects $2,500-$7,000. Free inspection. 770-895-2039.',
  keywords: 'crawl space waterproofing Stone Mountain GA, crawl space water DeKalb County, wet crawl space Stone Mountain, crawl space drainage Stone Mountain Georgia',
  openGraph: { title: 'Crawl Space Waterproofing in Stone Mountain, GA | Reliable Solutions Atlanta', description: 'Stop granite-driven water in your Stone Mountain crawl space. Free inspections. 770-895-2039.', url: 'https://www.waterhelpme.com/crawl-space-waterproofing/stone-mountain', type: 'website' },
  alternates: { canonical: 'https://www.waterhelpme.com/crawl-space-waterproofing/stone-mountain' },
}

const faqs = [
  { question: 'How much does crawl space waterproofing cost in Stone Mountain, GA?', answer: 'Crawl space waterproofing in Stone Mountain typically costs between $2,500 and $7,000. Stone Mountain homes are generally smaller which keeps costs lower. Interior drainage with sump pump starts around $2,000. Full waterproofing with granite-level drainage, vapor barrier, and block wall membrane runs $5,000 to $10,000.' },
  { question: 'Why does my Stone Mountain crawl space flood even in light rain?', answer: 'The granite monadnock extending underground across eastern DeKalb County is impermeable. Even light rain over a wide area channels along the rock surface and concentrates at the lowest point, which is often the crawl space. A small amount of rain over a large granite catchment area equals a large amount of water at your foundation.' },
  { question: 'Is a sump pump necessary for Stone Mountain crawl spaces?', answer: 'For homes on shallow granite, a sump pump is almost always required. The granite prevents drainage systems from going deep enough for gravity discharge to a daylight point. The pump lifts collected water above grade and discharges it away from the home. Battery backup is essential for storm-driven power outages.' },
  { question: 'Can you waterproof a cinder block crawl space?', answer: 'Yes. Cinder block crawl spaces are the most common type in Stone Mountain. The hollow blocks are porous and admit water through the faces and mortar joints. We install a drainage membrane on the interior block surface that captures weeping water and channels it to the perimeter drain. The vapor barrier then covers everything.' },
  { question: 'Will waterproofing stop termites in my Stone Mountain crawl space?', answer: 'Waterproofing removes the moisture conditions that termites need to survive. While it is not a pest treatment, a dry crawl space is significantly less attractive to subterranean termites than a wet one. We recommend continuing annual termite inspections and treatment alongside waterproofing for complete protection.' },
]

export default function CrawlSpaceWaterproofingStoneMountain() {
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Service', name: 'Crawl Space Waterproofing in Stone Mountain, GA', provider: { '@type': 'LocalBusiness', name: 'Reliable Solutions Atlanta', telephone: '+17708952039', url: 'https://www.waterhelpme.com', address: { '@type': 'PostalAddress', addressLocality: 'Stone Mountain', addressRegion: 'GA', addressCountry: 'US' }, areaServed: { '@type': 'City', name: 'Stone Mountain', containedIn: 'DeKalb County, GA' } }, serviceType: 'Crawl Space Waterproofing' }
  const faqJsonLd = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }

  return (
    <>
      <Header />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />

      <section className="relative bg-[#273373] py-16 sm:py-20 md:py-28"><div className="absolute inset-0 bg-gradient-to-br from-[#273373] to-[#115997] opacity-90" /><div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-white/70 text-sm font-medium mb-3 uppercase tracking-wider">DeKalb County, Georgia</p><h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-6 font-display leading-tight">Crawl Space Waterproofing in Stone Mountain, GA</h1><p className="text-white/80 text-lg sm:text-xl mb-8 leading-relaxed max-w-2xl">Crawl space waterproofing in Stone Mountain typically costs between $2,500 and $7,000. Reliable Solutions Atlanta stops the granite-channeled water that floods eastern DeKalb County crawl spaces with drainage systems built for the unique conditions created by shallow bedrock. Interior drainage, sump pumps, block wall membranes, and heavy-duty vapor barriers. Free same-week inspections.</p><div className="flex flex-col sm:flex-row gap-3"><Link href="/contact" className="inline-flex items-center justify-center gap-2 px-6 py-4 bg-white text-[#273373] font-bold rounded-xl hover:bg-gray-100 transition-colors">Schedule Free Inspection</Link><a href="tel:+17708952039" className="inline-flex items-center justify-center gap-2 px-6 py-4 bg-transparent border-2 border-white/30 text-white font-bold rounded-xl hover:bg-white/10 transition-colors">(770) 895-2039</a></div></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Why Stone Mountain Crawl Spaces Take On Water</h2><div className="prose prose-lg max-w-none text-gray-700"><p>Stone Mountain crawl space waterproofing is the most common service we perform in eastern DeKalb County because the granite substrata creates water conditions unlike anywhere else in metro Atlanta. The massive granite monadnock visible as Stone Mountain extends underground across the 30083, 30087, and 30088 zip codes as a shallow impermeable bedrock layer. Rain that falls on the surface soaks through the thin soil layer above the granite, hits the rock, and flows laterally along its surface until it finds the lowest point. That lowest point is often the crawl space beneath your home.</p><p>The 1960s through 1980s homes in Stone Mountain along Memorial Drive, Rockbridge Road, and Hairston Road were built on cinder block foundations with thin vapor barriers and open foundation vents. The cinder blocks are hollow and porous, freely admitting water that arrives under pressure from the granite channels. The mortar joints between blocks deteriorate over decades, creating additional pathways for water to enter. After 40 to 60 years of granite-driven water exposure, most Stone Mountain crawl spaces are in severe condition.</p><p>The thin soil layer over granite in Stone Mountain has limited water storage capacity. During even moderate rain, the soil saturates quickly and all additional water runs along the rock surface. This means Stone Mountain crawl spaces can flood from storms that cause no problems in areas with deeper soil profiles. Your neighbor 100 feet away on a different section of granite may stay dry while your crawl space takes on water, because the rock surface directs flow to your property specifically.</p></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Signs Your Stone Mountain Crawl Space Needs Waterproofing</h2><div className="grid sm:grid-cols-2 gap-4">{[{ title: 'Standing water after any rain', desc: 'If even moderate rain causes standing water in your crawl space, the granite is channeling water directly to your foundation. This volume of water requires active drainage and pumping, not just a vapor barrier.' },{ title: 'Cinder block walls visibly wet inside', desc: 'Water on the interior face of cinder block foundation walls means water is penetrating through the porous blocks from outside. The hollow block cores fill with water and weep through the inner face.' },{ title: 'Musty smell that permeates the entire house', desc: 'In Stone Mountain homes with severe crawl space moisture, the musty odor reaches every room through the HVAC system and natural air movement. The smell is constant, not seasonal.' },{ title: 'Floor joists showing dark staining or soft spots', desc: 'Wood structural members that are dark, soft to the touch, or crumble when probed have advanced moisture damage. This level of deterioration takes years of sustained high humidity to develop.' },{ title: 'Existing sump pump running constantly', desc: 'If you already have a sump pump and it runs frequently during wet seasons, the collection system feeding it is undersized for the water volume the granite delivers. The pump needs a larger drainage network.' },{ title: 'Vapor barrier floating on water', desc: 'If the existing vapor barrier has water pooling on top of it or is floating, water is entering with enough volume to overwhelm the barrier. The water needs to be captured and routed out before the barrier can function.' }].map((sign, i) => (<div key={i} className="bg-white rounded-xl p-5 shadow-sm"><h3 className="font-semibold text-[#273373] text-base mb-2">{sign.title}</h3><p className="text-gray-600 text-sm leading-relaxed">{sign.desc}</p></div>))}</div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">How We Waterproof Crawl Spaces in Stone Mountain</h2><div className="prose prose-lg max-w-none text-gray-700"><h3 className="text-[#273373] font-display">Granite-Level Perimeter Drainage</h3><p>We install the perimeter drain as deep as possible, ideally at or near the granite surface. This captures water flowing along the rock before it can pool on the crawl space floor. In areas where the granite is within 2 feet of the surface, we trench directly on top of the rock, using its impermeable surface as a natural drain floor. The pipe sits in gravel on the rock and collects water as it arrives.</p><h3 className="text-[#273373] font-display">Block Wall Drainage Membrane</h3><p>We install a dimpled drainage membrane on the interior face of the cinder block walls. Water weeping through the porous blocks hits the membrane and channels downward by gravity to the perimeter drain. This prevents water from spraying into the crawl space during high-pressure events and captures it at the wall before it reaches the floor or structure.</p><h3 className="text-[#273373] font-display">High-Capacity Sump with Battery Backup</h3><p>Stone Mountain granite channels can deliver high water volumes during storms. We size the sump pump for peak expected flow and include battery backup rated for 10+ hours. For homes with the most severe granite water, we install dual-pump systems where two pumps alternate to handle sustained high flow without burning out a single unit.</p><h3 className="text-[#273373] font-display">20-Mil Vapor Barrier Over Drainage System</h3><p>After the drainage system is managing the liquid water, we install a 20-mil reinforced vapor barrier across the entire floor and up the walls over the drainage membrane. The barrier prevents ground moisture vapor from entering the crawl space air while the drainage beneath handles the liquid. All seams are sealed and mechanically fastened.</p></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Crawl Space Waterproofing Costs in Stone Mountain</h2><div className="bg-white rounded-xl shadow-sm overflow-hidden"><table className="w-full"><thead className="bg-[#273373] text-white"><tr><th className="px-6 py-4 text-left text-sm font-semibold">Service</th><th className="px-6 py-4 text-left text-sm font-semibold">Typical Cost</th><th className="px-6 py-4 text-left text-sm font-semibold hidden sm:table-cell">Timeline</th></tr></thead><tbody className="divide-y divide-gray-100">{[['Vapor barrier (20-mil, floor + walls)', '$1,500 – $3,000', '1 day'],['Granite-level perimeter drain + sump', '$2,500 – $5,500', '1-2 days'],['Block wall drainage membrane', '$1,200 – $2,500', '1 day'],['Full waterproofing system', '$3,500 – $8,000', '2-3 days'],['Dual sump pump system', '$2,500 – $4,000', '1 day'],['Waterproofing + structural repair', '$5,000 – $12,000', '3-5 days']].map(([r, c, t], i) => (<tr key={i} className="hover:bg-gray-50"><td className="px-6 py-4 text-sm text-gray-900">{r}</td><td className="px-6 py-4 text-sm font-semibold text-[#115997]">{c}</td><td className="px-6 py-4 text-sm text-gray-500 hidden sm:table-cell">{t}</td></tr>))}</tbody></table></div><p className="text-sm text-gray-500 mt-4">Financing available through GreenSky with plans starting at 0% interest. All work includes warranty.</p></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-8 font-display">Frequently Asked Questions</h2><div className="space-y-4">{faqs.map((faq, i) => (<div key={i} className="bg-gray-50 rounded-xl p-6"><h3 className="font-semibold text-[#273373] text-lg mb-3">{faq.question}</h3><p className="text-gray-700 leading-relaxed">{faq.answer}</p></div>))}</div></div></section>

      <section className="py-12 sm:py-16 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-[#273373] mb-6 font-display">Related Services in Stone Mountain</h2><div className="grid sm:grid-cols-3 gap-4">{[{ title: 'Crawl Space Encapsulation', href: '/crawl-space-encapsulation/stone-mountain', desc: 'Seal and condition the crawl space after waterproofing for complete moisture elimination.' },{ title: 'Foundation Repair', href: '/foundation-repair/stone-mountain', desc: 'Repair granite-affected foundation damage alongside crawl space waterproofing.' },{ title: 'Drainage Solutions', href: '/drainage/stone-mountain', desc: 'Exterior drainage designed for granite substrata to reduce water reaching the crawl space.' }].map((s, i) => (<Link key={i} href={s.href} className="bg-white rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow group"><h3 className="font-semibold text-[#273373] mb-2 group-hover:text-[#115997] transition-colors">{s.title}</h3><p className="text-gray-600 text-sm">{s.desc}</p></Link>))}</div></div></section>

      <section className="py-12 sm:py-16 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-[#273373] mb-6 font-display">Learn More About Crawl Spaces</h2><div className="grid sm:grid-cols-2 gap-4">{[{ title: 'Crawl Space Encapsulation vs Waterproofing', href: '/blog/crawl-space-encapsulation-vs-waterproofing' }, { title: 'Crawl Space Mold: Signs and Solutions', href: '/blog/crawl-space-mold-signs' }, { title: 'Crawl Space Vapor Barrier Guide', href: '/blog/crawl-space-vapor-barrier-guide' }, { title: 'Sump Pump Maintenance Guide', href: '/blog/sump-pump-maintenance-guide' }].map((p, i) => (<Link key={i} href={p.href} className="flex items-center gap-3 p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors"><svg className="w-5 h-5 text-[#115997] flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg><span className="text-sm font-medium text-gray-800">{p.title}</span></Link>))}</div></div></section>

      <section className="py-8 bg-gray-50 border-t border-gray-200"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><p className="text-sm text-gray-500 mb-4"><Link href="/" className="hover:text-[#115997]">Home</Link> {' / '}<Link href="/crawl-space-waterproofing" className="hover:text-[#115997]">Crawl Space Waterproofing</Link> {' / '}<span className="text-gray-700">Stone Mountain</span></p><p className="text-sm text-gray-500">Crawl space waterproofing also available in <Link href="/crawl-space-waterproofing/lawrenceville" className="text-[#115997] hover:underline">Lawrenceville</Link>, <Link href="/crawl-space-waterproofing/marietta" className="text-[#115997] hover:underline">Marietta</Link>, <Link href="/crawl-space-waterproofing/roswell" className="text-[#115997] hover:underline">Roswell</Link>, <Link href="/crawl-space-waterproofing/alpharetta" className="text-[#115997] hover:underline">Alpharetta</Link>, <Link href="/crawl-space-waterproofing/decatur" className="text-[#115997] hover:underline">Decatur</Link>, and <Link href="/crawl-space-waterproofing/sandy-springs" className="text-[#115997] hover:underline">Sandy Springs</Link>.</p></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-[#115997]"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-4 font-display">Free Crawl Space Inspection in Stone Mountain</h2><p className="text-white/80 text-lg mb-8 max-w-2xl mx-auto">We know how water moves through Stone Mountain granite. We will inspect your crawl space, identify the water sources, and design a waterproofing system that handles the volume your property receives. No obligation.</p><div className="flex flex-col sm:flex-row gap-3 justify-center"><Link href="/contact" className="inline-flex items-center justify-center px-8 py-4 bg-white text-[#273373] font-bold rounded-xl hover:bg-gray-100 transition-colors text-lg">Schedule Free Inspection</Link><a href="tel:+17708952039" className="inline-flex items-center justify-center px-8 py-4 border-2 border-white text-white font-bold rounded-xl hover:bg-white/10 transition-colors text-lg">Call (770) 895-2039</a></div><p className="text-white/50 text-sm mt-6">BBB A+ Accredited · IICRC Certified · 20+ Years Experience · Financing Available</p></div></section>
      <Footer />
    </>
  )
}