import Link from 'next/link'
import Header from '../../components/Header'
import Footer from '../../components/Footer'

export const metadata = {
  title: 'Crawl Space Waterproofing in Sandy Springs, GA | Free Inspection | Reliable Solutions Atlanta',
  description: 'Crawl space waterproofing in Sandy Springs, GA. Interior drainage and vapor barriers for 1960s-1980s ranches and split-levels on hilly terrain. Most projects $3,000-$9,000. Free inspection. 770-895-2039.',
  keywords: 'crawl space waterproofing Sandy Springs GA, crawl space water Sandy Springs, wet crawl space Sandy Springs Georgia, crawl space drainage Sandy Springs',
  openGraph: { title: 'Crawl Space Waterproofing in Sandy Springs, GA | Reliable Solutions Atlanta', description: 'Stop water in your Sandy Springs crawl space. Free inspections. 770-895-2039.', url: 'https://www.waterhelpme.com/crawl-space-waterproofing/sandy-springs', type: 'website' },
  alternates: { canonical: 'https://www.waterhelpme.com/crawl-space-waterproofing/sandy-springs' },
}

const faqs = [
  { question: 'How much does crawl space waterproofing cost in Sandy Springs, GA?', answer: 'Crawl space waterproofing in Sandy Springs typically costs between $3,000 and $9,000. Split-level homes with partial crawl spaces cost less than full crawl space ranches. Interior drainage with sump pump starts around $2,500. Full waterproofing with targeted drainage for granite soil channels runs $5,000 to $12,000.' },
  { question: 'Why does my Sandy Springs crawl space flood in specific spots?', answer: 'Sandy Springs soil contains decomposed granite mixed with clay. The granite creates fast-draining pockets that channel water to specific locations along the foundation rather than distributing it evenly. This means water enters the crawl space at concentrated points while other sections stay relatively dry. Targeted drainage at these entry points is the most efficient solution.' },
  { question: 'Can you waterproof just the crawl space part of my Sandy Springs split-level?', answer: 'Yes. Sandy Springs split-levels often have a crawl space under one section and a basement or slab under another. We waterproof the crawl space section independently and seal the transition between foundation types to prevent moisture migration. This targeted approach is common and cost-effective for split-level homes.' },
  { question: 'Will crawl space waterproofing help my Sandy Springs home inspection?', answer: 'A waterproofed crawl space with documentation and transferable warranty eliminates one of the most common inspection findings in Sandy Springs real estate transactions. Homes with professional waterproofing sell faster and for higher prices than comparable homes with unresolved moisture issues.' },
  { question: 'Do I need waterproofing or encapsulation for my Sandy Springs crawl space?', answer: 'If your crawl space has active water entry, you need waterproofing first to stop the water. Encapsulation addresses the humidity and air quality but cannot handle liquid water. Many Sandy Springs homeowners start with waterproofing and add encapsulation later, or we do both at once for a complete solution.' },
]

export default function CrawlSpaceWaterproofingSandySprings() {
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Service', name: 'Crawl Space Waterproofing in Sandy Springs, GA', provider: { '@type': 'LocalBusiness', name: 'Reliable Solutions Atlanta', telephone: '+17708952039', url: 'https://www.waterhelpme.com', address: { '@type': 'PostalAddress', addressLocality: 'Sandy Springs', addressRegion: 'GA', addressCountry: 'US' }, areaServed: { '@type': 'City', name: 'Sandy Springs', containedIn: 'Fulton County, GA' } }, serviceType: 'Crawl Space Waterproofing' }
  const faqJsonLd = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.question, acceptedAnswer: { '@type': 'Answer', text: f.answer } })) }

  return (
    <>
      <Header />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />

      <section className="relative bg-[#273373] py-16 sm:py-20 md:py-28"><div className="absolute inset-0 bg-gradient-to-br from-[#273373] to-[#115997] opacity-90" /><div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-white/70 text-sm font-medium mb-3 uppercase tracking-wider">Fulton County, Georgia</p><h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-6 font-display leading-tight">Crawl Space Waterproofing in Sandy Springs, GA</h1><p className="text-white/80 text-lg sm:text-xl mb-8 leading-relaxed max-w-2xl">Crawl space waterproofing in Sandy Springs typically costs between $3,000 and $9,000. Reliable Solutions Atlanta stops water in Sandy Springs crawl spaces with drainage systems designed for the decomposed granite soil that channels water in unpredictable concentrated flows. Interior drainage, sump pumps, and vapor barriers for ranches and split-levels. Free same-week inspections.</p><div className="flex flex-col sm:flex-row gap-3"><Link href="/contact" className="inline-flex items-center justify-center gap-2 px-6 py-4 bg-white text-[#273373] font-bold rounded-xl hover:bg-gray-100 transition-colors">Schedule Free Inspection</Link><a href="tel:+17708952039" className="inline-flex items-center justify-center gap-2 px-6 py-4 bg-transparent border-2 border-white/30 text-white font-bold rounded-xl hover:bg-white/10 transition-colors">(770) 895-2039</a></div></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Why Sandy Springs Crawl Spaces Take On Water</h2><div className="prose prose-lg max-w-none text-gray-700"><p>Sandy Springs crawl spaces flood because the hilly terrain and unique soil composition create concentrated water delivery patterns that the original minimal waterproofing cannot handle. The ranches and split-levels built along Roswell Road, Mount Vernon Highway, Riverside Drive, and the Powers Ferry corridor in the 1960s through 1980s sit on slopes that channel runoff directly toward the foundation.</p><p>The decomposed granite mixed into Sandy Springs clay soil is the key differentiator from other metro Atlanta suburbs. Unlike uniform clay that seeps water evenly, granite particles create fast-draining pockets that channel water in concentrated streams. These streams follow the path of least resistance through the soil and arrive at the crawl space wall at specific points with enough pressure to push through cinder block, through mortar joints, and under the foundation footer.</p><p>The 30328, 30342, and 30350 zip codes all have homes with this characteristic uneven water entry. The western Sandy Springs neighborhoods near the Chattahoochee have the additional challenge of a seasonally elevated water table that pushes moisture up through the crawl space floor during prolonged wet periods.</p><p>Sandy Springs home turnover drives many waterproofing projects. Every real estate transaction triggers a professional home inspection, and wet crawl spaces are among the most commonly flagged findings. Sellers who address the issue before listing avoid deal complications. Buyers who inherit the problem need it fixed before the moisture causes further structural damage.</p></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Signs Your Sandy Springs Crawl Space Needs Waterproofing</h2><div className="grid sm:grid-cols-2 gap-4">{[{ title: 'Water at specific wall spots, not everywhere', desc: 'Granite soil channels water to concentrated entry points. If water enters at one or two locations on the wall while the rest stays dry, the granite substrate is funneling water to those specific spots.' },{ title: 'Standing water after moderate rain', desc: 'If even moderate rain causes standing water in the crawl space that takes days to recede, the original drainage and damproofing have failed. The water volume exceeds what evaporation can handle.' },{ title: 'Wet soil on the uphill side of a split-level', desc: 'Split-level crawl spaces on slopes receive concentrated hillside runoff on the buried wall. If the uphill section of the crawl space is consistently wetter than the downhill section, hillside water is the primary source.' },{ title: 'Cold drafts through the floor in winter', desc: 'Sandy Springs crawl spaces with open vents and water damage often have gaps in the floor system that allow cold air to enter the living space. Cold feet on the first floor in winter points to a crawl space problem.' },{ title: 'Home inspector flagged moisture or mold', desc: 'If a recent inspection found moisture, mold, or wood damage in the crawl space, these findings need professional waterproofing. Inspector recommendations carry weight in Sandy Springs real estate negotiations.' },{ title: 'Pest company recommending moisture reduction', desc: 'Termite inspectors who find moisture conditions or active termite damage in the crawl space are identifying the root cause. Pest treatment without moisture control leads to reinfestation.' }].map((sign, i) => (<div key={i} className="bg-white rounded-xl p-5 shadow-sm"><h3 className="font-semibold text-[#273373] text-base mb-2">{sign.title}</h3><p className="text-gray-600 text-sm leading-relaxed">{sign.desc}</p></div>))}</div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">How We Waterproof Crawl Spaces in Sandy Springs</h2><div className="prose prose-lg max-w-none text-gray-700"><h3 className="text-[#273373] font-display">Targeted Drainage at Granite Entry Points</h3><p>We identify where the granite substrate is channeling water to the foundation and install drainage at those specific points. This may mean draining one wall and half of another rather than the full perimeter. We probe the soil during assessment to map the granite veins and predict where water will arrive during future rain events.</p><h3 className="text-[#273373] font-display">Split-Level Transition Sealing</h3><p>Where the crawl space meets a basement or slab section in Sandy Springs split-levels, we seal the transition with hydraulic cement and flexible membrane. This prevents water or moisture from migrating between foundation types through the joint that builders left open during original construction.</p><h3 className="text-[#273373] font-display">Sump Pump with Hillside Gravity Discharge</h3><p>Sandy Springs slopes provide natural gravity discharge on the downhill side. The sump pump discharge line exits through the downhill wall and uses gravity to carry water away. The pump activates during peak events, but gravity handles the ongoing discharge, extending pump life and reducing energy use.</p><h3 className="text-[#273373] font-display">Vapor Barrier with Block Wall Membrane</h3><p>Cinder block walls in Sandy Springs 1960s-1980s homes admit moisture through the hollow cores. We install a drainage membrane on the block wall face that captures weeping water and channels it to the perimeter drain. The 20-mil vapor barrier then covers the floor and overlaps the wall membrane, creating a continuous moisture barrier.</p></div></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-6 font-display">Crawl Space Waterproofing Costs in Sandy Springs</h2><div className="bg-white rounded-xl shadow-sm overflow-hidden"><table className="w-full"><thead className="bg-[#273373] text-white"><tr><th className="px-6 py-4 text-left text-sm font-semibold">Service</th><th className="px-6 py-4 text-left text-sm font-semibold">Typical Cost</th><th className="px-6 py-4 text-left text-sm font-semibold hidden sm:table-cell">Timeline</th></tr></thead><tbody className="divide-y divide-gray-100">{[['Targeted drainage (1-2 walls)', '$2,000 – $4,500', '1-2 days'],['Full perimeter drain + sump', '$3,500 – $8,000', '2-3 days'],['Vapor barrier (20-mil, floor + walls)', '$2,000 – $4,500', '1 day'],['Block wall drainage membrane', '$1,500 – $3,000', '1 day'],['Split-level transition sealing', '$500 – $1,200', 'Same day'],['Complete waterproofing system', '$4,000 – $12,000', '2-4 days']].map(([r, c, t], i) => (<tr key={i} className="hover:bg-gray-50"><td className="px-6 py-4 text-sm text-gray-900">{r}</td><td className="px-6 py-4 text-sm font-semibold text-[#115997]">{c}</td><td className="px-6 py-4 text-sm text-gray-500 hidden sm:table-cell">{t}</td></tr>))}</tbody></table></div><p className="text-sm text-gray-500 mt-4">Financing available through GreenSky. Transferable warranty included.</p></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-[#273373] mb-8 font-display">Frequently Asked Questions</h2><div className="space-y-4">{faqs.map((faq, i) => (<div key={i} className="bg-gray-50 rounded-xl p-6"><h3 className="font-semibold text-[#273373] text-lg mb-3">{faq.question}</h3><p className="text-gray-700 leading-relaxed">{faq.answer}</p></div>))}</div></div></section>

      <section className="py-12 sm:py-16 bg-gray-50"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-[#273373] mb-6 font-display">Related Services in Sandy Springs</h2><div className="grid sm:grid-cols-3 gap-4">{[{ title: 'Crawl Space Encapsulation', href: '/crawl-space-encapsulation/sandy-springs', desc: 'Seal and condition the crawl space after waterproofing for complete moisture control.' },{ title: 'Foundation Repair', href: '/foundation-repair/sandy-springs', desc: 'Fix split-level foundation damage caused by the same water affecting the crawl space.' },{ title: 'Drainage Solutions', href: '/drainage/sandy-springs', desc: 'Exterior hillside drainage reduces the water reaching your crawl space.' }].map((s, i) => (<Link key={i} href={s.href} className="bg-white rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow group"><h3 className="font-semibold text-[#273373] mb-2 group-hover:text-[#115997] transition-colors">{s.title}</h3><p className="text-gray-600 text-sm">{s.desc}</p></Link>))}</div></div></section>

      <section className="py-12 sm:py-16 bg-white"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold text-[#273373] mb-6 font-display">Learn More About Crawl Spaces</h2><div className="grid sm:grid-cols-2 gap-4">{[{ title: 'Crawl Space Encapsulation vs Waterproofing', href: '/blog/crawl-space-encapsulation-vs-waterproofing' }, { title: 'Crawl Space Vapor Barrier Guide', href: '/blog/crawl-space-vapor-barrier-guide' }, { title: 'Crawl Space Mold: Signs and Solutions', href: '/blog/crawl-space-mold-signs' }, { title: 'Crawl Space Repair Cost in Atlanta', href: '/blog/crawl-space-repair-cost-atlanta' }].map((p, i) => (<Link key={i} href={p.href} className="flex items-center gap-3 p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors"><svg className="w-5 h-5 text-[#115997] flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg><span className="text-sm font-medium text-gray-800">{p.title}</span></Link>))}</div></div></section>

      <section className="py-8 bg-gray-50 border-t border-gray-200"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><p className="text-sm text-gray-500 mb-4"><Link href="/" className="hover:text-[#115997]">Home</Link> {' / '}<Link href="/crawl-space-waterproofing" className="hover:text-[#115997]">Crawl Space Waterproofing</Link> {' / '}<span className="text-gray-700">Sandy Springs</span></p><p className="text-sm text-gray-500">Crawl space waterproofing also available in <Link href="/crawl-space-waterproofing/lawrenceville" className="text-[#115997] hover:underline">Lawrenceville</Link>, <Link href="/crawl-space-waterproofing/marietta" className="text-[#115997] hover:underline">Marietta</Link>, <Link href="/crawl-space-waterproofing/roswell" className="text-[#115997] hover:underline">Roswell</Link>, <Link href="/crawl-space-waterproofing/alpharetta" className="text-[#115997] hover:underline">Alpharetta</Link>, <Link href="/crawl-space-waterproofing/decatur" className="text-[#115997] hover:underline">Decatur</Link>, and <Link href="/crawl-space-waterproofing/stone-mountain" className="text-[#115997] hover:underline">Stone Mountain</Link>.</p></div></section>

      <section className="py-12 sm:py-16 md:py-20 bg-[#115997]"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-4 font-display">Free Crawl Space Inspection in Sandy Springs</h2><p className="text-white/80 text-lg mb-8 max-w-2xl mx-auto">Selling, buying, or just tired of a wet crawl space? We will inspect it, trace the water sources, and give you a clear waterproofing plan. No obligation.</p><div className="flex flex-col sm:flex-row gap-3 justify-center"><Link href="/contact" className="inline-flex items-center justify-center px-8 py-4 bg-white text-[#273373] font-bold rounded-xl hover:bg-gray-100 transition-colors text-lg">Schedule Free Inspection</Link><a href="tel:+17708952039" className="inline-flex items-center justify-center px-8 py-4 border-2 border-white text-white font-bold rounded-xl hover:bg-white/10 transition-colors text-lg">Call (770) 895-2039</a></div><p className="text-white/50 text-sm mt-6">BBB A+ Accredited · IICRC Certified · 20+ Years Experience · Financing Available</p></div></section>
      <Footer />
    </>
  )
}